# Generated by Django 5.2.4 on 2025-07-21 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="account",
            new_name="account_id",
        ),
    ]
