# Generated by Django 5.2.4 on 2025-07-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_rename_account_transaction_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
